### ISSUE TITLE
App buttons in japanese only?

### ISSUE THREAD

**Issue by nathaniel** [tmurakam/presentationtimer#2]
I have been using Presentation Timer for a few years (thanks for a great app!)
For the last several months (maybe since latest version 4.3.0 update?) The app buttons to start/stop/reset the timer, or "OK" from the Info screen, are only labeled in Japanese (or at least a language whose characters I don't recognize)!

I confirmed that I have no languages other than English set up in my iPhone settings.

![IMG_3546](https://user-images.githubusercontent.com/68211/195672188-f663a08e-4cda-44f4-b428-2552b81c7700.PNG)
![IMG_3545](https://user-images.githubusercontent.com/68211/195672194-bcd69401-0cd2-42c2-b6ea-8e901da0f4cb.PNG)
![IMG_3544](https://user-images.githubusercontent.com/68211/195672197-06b65c21-a9eb-4294-9ef6-f074a67c7cfd.PNG)

**Comment by tmurakam** [comment]
Fixed with ver 4.4.0.
